import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import type { StudioDesignSystemDefinition, StudioTemplateCategory, StudioTemplateDefinition } from './types.ts'

const BUILTIN_SKILLS_ROOT = join(process.cwd(), 'apps', 'electron', 'resources', 'builtin-skills')

const DEFINITIONS: Array<Omit<StudioTemplateDefinition, 'templatePath' | 'componentPaths' | 'category' | 'recommendedDesignSystem'>> = [
  { id: 'landing-saas', title: 'SaaS Landing Page', description: 'Polished SaaS marketing page with hero, features, pricing, and FAQ.', type: 'landing-page', skill: 'studio-prototype', tags: ['landing', 'saas', 'marketing'] },
  { id: 'landing-agent', title: 'Agent Product Landing Page', description: 'Agent-focused landing page with workflow, trust, and CTA sections.', type: 'landing-page', skill: 'studio-prototype', tags: ['landing', 'agent', 'product'] },
  { id: 'landing-mobile-app', title: 'Mobile App Landing Page', description: 'App launch page with phone-first product story and conversion sections.', type: 'landing-page', skill: 'studio-prototype', tags: ['landing', 'mobile', 'app'] },
  { id: 'landing-web-app', title: 'Web App Product Page', description: 'Web app launch page with workflow, integrations, and pricing preview.', type: 'landing-page', skill: 'studio-prototype', tags: ['landing', 'web-app', 'product'] },
  { id: 'prototype-mobile-flow', title: 'Mobile Flow Prototype', description: 'Mobile product flow prototype with onboarding, action, and success states.', type: 'prototype', skill: 'studio-prototype', tags: ['prototype', 'mobile', 'flow'] },
  { id: 'prototype-saas-flow', title: 'SaaS Flow Prototype', description: 'SaaS workflow prototype with setup, command center, detail, and outcome screens.', type: 'prototype', skill: 'studio-prototype', tags: ['prototype', 'saas', 'workflow'] },
  { id: 'commerce-storefront', title: 'Commerce Storefront', description: 'Modern storefront with editorial hero, product grid, trust strip, and checkout CTA.', type: 'prototype', skill: 'studio-prototype', tags: ['commerce', 'storefront', 'product'] },
  { id: 'portfolio-case-study', title: 'Portfolio Case Study', description: 'Case study page for portfolio storytelling, process, outcomes, and contact CTA.', type: 'prototype', skill: 'studio-prototype', tags: ['portfolio', 'case-study', 'story'] },
  { id: 'dashboard-analytics', title: 'Analytics Dashboard', description: 'Metrics-heavy dashboard with cards, chart panels, and activity table.', type: 'dashboard', skill: 'studio-dashboard', tags: ['dashboard', 'analytics', 'metrics'] },
  { id: 'dashboard-admin', title: 'Admin Dashboard', description: 'Admin console with sidebar, status cards, table, and actions.', type: 'dashboard', skill: 'studio-dashboard', tags: ['dashboard', 'admin', 'ops'] },
  { id: 'dashboard-finance', title: 'Finance Dashboard', description: 'Finance operations dashboard with runway, variance, cashflow, and export summary.', type: 'dashboard', skill: 'studio-dashboard', tags: ['dashboard', 'finance', 'ops'] },
  { id: 'dashboard-support', title: 'Support Command Center', description: 'Support dashboard with queue health, SLA, incidents, and knowledge gaps.', type: 'dashboard', skill: 'studio-dashboard', tags: ['dashboard', 'support', 'ops'] },
  { id: 'dashboard-ai-ops', title: 'AI Ops Dashboard', description: 'AI operations dashboard with model health, run stream, guardrails, and optimization.', type: 'dashboard', skill: 'studio-dashboard', tags: ['dashboard', 'ai', 'ops'] },
  { id: 'dashboard-crm', title: 'CRM Pipeline Dashboard', description: 'Sales pipeline dashboard with revenue stages, deals, activity, and coaching insights.', type: 'dashboard', skill: 'studio-dashboard', tags: ['dashboard', 'crm', 'sales'] },
  { id: 'deck-pitch', title: 'Pitch Deck', description: 'Narrative pitch deck structure for product, market, proof, and ask.', type: 'deck', skill: 'studio-deck', tags: ['deck', 'pitch', 'slides'] },
  { id: 'deck-product', title: 'Product Brief Deck', description: 'Product strategy deck with problem, solution, roadmap, and metrics.', type: 'deck', skill: 'studio-deck', tags: ['deck', 'product', 'brief'] },
  { id: 'deck-case-study', title: 'Case Study Deck', description: 'Customer story deck with challenge, solution, impact, and replication path.', type: 'deck', skill: 'studio-deck', tags: ['deck', 'case-study', 'customer'] },
  { id: 'deck-investor-update', title: 'Investor Update Deck', description: 'Investor update with highlights, metrics, roadmap, and support needed.', type: 'deck', skill: 'studio-deck', tags: ['deck', 'investor', 'update'] },
  { id: 'deck-design-review', title: 'Design Review Deck', description: 'Design critique deck with context, options, recommendation, and decision log.', type: 'deck', skill: 'studio-deck', tags: ['deck', 'design', 'review'] },
  { id: 'report-research', title: 'Research Report', description: 'Decision-ready research report with summary, evidence, implications, and next steps.', type: 'report', skill: 'studio-report', tags: ['report', 'research', 'analysis'] },
  { id: 'report-product-spec', title: 'Product Spec Report', description: 'Product spec report with problem, scope, acceptance criteria, and launch plan.', type: 'report', skill: 'studio-report', tags: ['report', 'product', 'spec'] },
  { id: 'report-design-system', title: 'Design System Report', description: 'Design system report with foundations, components, patterns, and governance.', type: 'report', skill: 'studio-report', tags: ['report', 'design-system', 'components'] },
  { id: 'image-brand-visual', title: 'Brand Visual Prompt Board', description: 'Image prompt board for brand visuals, art direction, variants, and usage.', type: 'image-prompt', skill: 'studio-image', tags: ['image', 'prompt', 'brand'] },
  { id: 'image-product-mockup', title: 'Product Mockup Prompt Board', description: 'Image prompt board for product mockups, UI states, scenes, and variants.', type: 'image-prompt', skill: 'studio-image', tags: ['image', 'prompt', 'mockup'] },
  { id: 'video-launch-storyboard', title: 'Launch Video Storyboard', description: 'Video storyboard for product launch hook, problem, reveal, and CTA.', type: 'video-prompt', skill: 'studio-video', tags: ['video', 'storyboard', 'launch'] },
  { id: 'video-product-demo', title: 'Product Demo Storyboard', description: 'Video storyboard for product demo setup, walkthrough, outcome, and cutdowns.', type: 'video-prompt', skill: 'studio-video', tags: ['video', 'demo', 'storyboard'] },
  { id: 'agency-home', title: 'Agency Homepage', description: 'Agency homepage with positioning, services, proof, and conversion path.', type: 'prototype', skill: 'studio-prototype', tags: ['agency', 'web'] },
  { id: 'startup-waitlist', title: 'Startup Waitlist', description: 'Waitlist page for early access, product promise, proof, and signup CTA.', type: 'landing-page', skill: 'studio-prototype', tags: ['startup', 'waitlist'] },
  { id: 'docs-home', title: 'Documentation Home', description: 'Developer documentation homepage with guides, API paths, and quick starts.', type: 'prototype', skill: 'studio-prototype', tags: ['docs', 'developer'] },
  { id: 'changelog-page', title: 'Changelog Page', description: 'Product changelog page for releases, tags, and update storytelling.', type: 'prototype', skill: 'studio-prototype', tags: ['changelog', 'updates'] },
  { id: 'community-home', title: 'Community Home', description: 'Community landing page with member value, events, and participation CTAs.', type: 'prototype', skill: 'studio-prototype', tags: ['community', 'social'] },
  { id: 'settings-screen', title: 'Settings Screen', description: 'App settings screen with preferences, account, security, and workspace sections.', type: 'prototype', skill: 'studio-prototype', tags: ['settings', 'app'] },
  { id: 'inbox-screen', title: 'Inbox Screen', description: 'Inbox productivity screen with messages, filters, and detail preview.', type: 'prototype', skill: 'studio-prototype', tags: ['inbox', 'messages'] },
  { id: 'kanban-board', title: 'Kanban Board', description: 'Workflow board with columns, cards, owners, status, and action controls.', type: 'prototype', skill: 'studio-prototype', tags: ['kanban', 'workflow'] },
  { id: 'billing-screen', title: 'Billing Screen', description: 'Billing and subscription screen with plan, invoices, payment, and usage.', type: 'prototype', skill: 'studio-prototype', tags: ['billing', 'account'] },
  { id: 'command-center', title: 'Command Center', description: 'Workspace command center with overview, actions, tasks, and status.', type: 'prototype', skill: 'studio-prototype', tags: ['command', 'workspace'] },
  { id: 'mobile-profile', title: 'Mobile Profile', description: 'Mobile profile screen with identity, stats, activity, and actions.', type: 'prototype', skill: 'studio-prototype', tags: ['mobile', 'profile'] },
  { id: 'mobile-paywall', title: 'Mobile Paywall', description: 'Mobile paywall screen with value, plans, trial, and trust cues.', type: 'prototype', skill: 'studio-prototype', tags: ['mobile', 'paywall'] },
  { id: 'mobile-chat', title: 'Mobile Chat', description: 'Mobile chat screen with conversation, composer, and assistant states.', type: 'prototype', skill: 'studio-prototype', tags: ['mobile', 'chat'] },
  { id: 'mobile-activity', title: 'Mobile Activity', description: 'Mobile activity feed with timeline, filters, and detail states.', type: 'prototype', skill: 'studio-prototype', tags: ['mobile', 'activity'] },
  { id: 'desktop-editor', title: 'Desktop Editor', description: 'Desktop editor layout with toolbar, canvas, inspector, and status bar.', type: 'prototype', skill: 'studio-prototype', tags: ['desktop', 'editor'] },
  { id: 'desktop-file-manager', title: 'Desktop File Manager', description: 'Desktop file manager with sidebar, grid, preview, and metadata.', type: 'prototype', skill: 'studio-prototype', tags: ['desktop', 'files'] },
  { id: 'desktop-inspector', title: 'Desktop Inspector', description: 'Desktop inspector panel for object details, properties, and actions.', type: 'prototype', skill: 'studio-prototype', tags: ['desktop', 'inspector'] },
  { id: 'dashboard-security', title: 'Security Dashboard', description: 'Security dashboard with risk, alerts, posture, and investigation queue.', type: 'dashboard', skill: 'studio-dashboard', tags: ['security', 'dashboard'] },
  { id: 'dashboard-observability', title: 'Observability Dashboard', description: 'Observability dashboard with services, logs, traces, and incidents.', type: 'dashboard', skill: 'studio-dashboard', tags: ['observability', 'logs'] },
  { id: 'dashboard-marketing', title: 'Marketing Dashboard', description: 'Marketing dashboard with campaigns, funnel, attribution, and channel mix.', type: 'dashboard', skill: 'studio-dashboard', tags: ['marketing', 'analytics'] },
  { id: 'dashboard-product', title: 'Product Analytics Dashboard', description: 'Product analytics dashboard with activation, retention, cohorts, and events.', type: 'dashboard', skill: 'studio-dashboard', tags: ['product', 'analytics'] },
  { id: 'dashboard-infra', title: 'Infrastructure Dashboard', description: 'Infrastructure dashboard with capacity, health, deploys, and alerts.', type: 'dashboard', skill: 'studio-dashboard', tags: ['infra', 'ops'] },
  { id: 'deck-sales', title: 'Sales Deck', description: 'Sales deck with pain, product, proof, ROI, and next steps.', type: 'deck', skill: 'studio-deck', tags: ['sales', 'deck'] },
  { id: 'deck-roadmap', title: 'Roadmap Deck', description: 'Roadmap deck with strategy, milestones, bets, and dependencies.', type: 'deck', skill: 'studio-deck', tags: ['roadmap', 'deck'] },
  { id: 'deck-launch', title: 'Launch Deck', description: 'Launch deck with audience, plan, channels, timeline, and risks.', type: 'deck', skill: 'studio-deck', tags: ['launch', 'deck'] },
  { id: 'deck-board-update', title: 'Board Update Deck', description: 'Board update deck with highlights, metrics, risks, and asks.', type: 'deck', skill: 'studio-deck', tags: ['board', 'update'] },
  { id: 'report-audit', title: 'Audit Report', description: 'Audit report with findings, evidence, severity, and remediation plan.', type: 'report', skill: 'studio-report', tags: ['audit', 'report'] },
  { id: 'report-qa', title: 'QA Report', description: 'QA report with coverage, failures, risk, and release recommendation.', type: 'report', skill: 'studio-report', tags: ['qa', 'quality'] },
  { id: 'report-strategy-memo', title: 'Strategy Memo', description: 'Strategy memo with context, options, recommendation, and decision log.', type: 'report', skill: 'studio-report', tags: ['strategy', 'memo'] },
  { id: 'report-research-synthesis', title: 'Research Synthesis', description: 'Research synthesis with themes, evidence, implications, and decisions.', type: 'report', skill: 'studio-report', tags: ['research', 'synthesis'] },
  { id: 'image-campaign-board', title: 'Campaign Image Board', description: 'Image prompt board for campaign directions, variants, and usage.', type: 'image-prompt', skill: 'studio-image', tags: ['image', 'campaign'] },
  { id: 'image-social-pack', title: 'Social Image Pack', description: 'Image prompt pack for social assets, aspect ratios, and variants.', type: 'image-prompt', skill: 'studio-image', tags: ['image', 'social'] },
  { id: 'video-ad-storyboard', title: 'Ad Storyboard', description: 'Video ad storyboard with hook, product reveal, proof, and CTA.', type: 'video-prompt', skill: 'studio-video', tags: ['video', 'ad'] },
  { id: 'video-onboarding-flow', title: 'Onboarding Video Flow', description: 'Onboarding video flow with steps, narration, and cutdowns.', type: 'video-prompt', skill: 'studio-video', tags: ['video', 'onboarding'] },
]


const TEMPLATE_METADATA: Record<string, { category: StudioTemplateCategory; recommendedDesignSystem: string }> = {
  'landing-saas': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'landing-agent': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'landing-mobile-app': { category: 'mobile', recommendedDesignSystem: 'consumer-mobile' },
  'landing-web-app': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'prototype-mobile-flow': { category: 'mobile', recommendedDesignSystem: 'consumer-mobile' },
  'prototype-saas-flow': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'commerce-storefront': { category: 'web', recommendedDesignSystem: 'commerce-editorial' },
  'portfolio-case-study': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'dashboard-analytics': { category: 'dashboard', recommendedDesignSystem: 'executive-analytics' },
  'dashboard-admin': { category: 'dashboard', recommendedDesignSystem: 'dense-ops' },
  'dashboard-finance': { category: 'dashboard', recommendedDesignSystem: 'executive-analytics' },
  'dashboard-support': { category: 'dashboard', recommendedDesignSystem: 'dense-ops' },
  'dashboard-ai-ops': { category: 'dashboard', recommendedDesignSystem: 'ai-command' },
  'dashboard-crm': { category: 'dashboard', recommendedDesignSystem: 'executive-analytics' },
  'deck-pitch': { category: 'deck', recommendedDesignSystem: 'pitch-dark' },
  'deck-product': { category: 'deck', recommendedDesignSystem: 'strategy-light' },
  'deck-case-study': { category: 'deck', recommendedDesignSystem: 'strategy-light' },
  'deck-investor-update': { category: 'deck', recommendedDesignSystem: 'pitch-dark' },
  'deck-design-review': { category: 'deck', recommendedDesignSystem: 'strategy-light' },
  'report-research': { category: 'report', recommendedDesignSystem: 'research-paper' },
  'report-product-spec': { category: 'report', recommendedDesignSystem: 'product-spec' },
  'report-design-system': { category: 'report', recommendedDesignSystem: 'product-spec' },
  'image-brand-visual': { category: 'image', recommendedDesignSystem: 'brand-visual' },
  'image-product-mockup': { category: 'image', recommendedDesignSystem: 'product-mockup' },
  'video-launch-storyboard': { category: 'video', recommendedDesignSystem: 'launch-motion' },
  'video-product-demo': { category: 'video', recommendedDesignSystem: 'demo-storyboard' },
  'agency-home': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'startup-waitlist': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'docs-home': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'changelog-page': { category: 'web', recommendedDesignSystem: 'saas-modern' },
  'community-home': { category: 'web', recommendedDesignSystem: 'consumer-mobile' },
  'settings-screen': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'inbox-screen': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'kanban-board': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'billing-screen': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'command-center': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'mobile-profile': { category: 'mobile', recommendedDesignSystem: 'consumer-mobile' },
  'mobile-paywall': { category: 'mobile', recommendedDesignSystem: 'consumer-mobile' },
  'mobile-chat': { category: 'mobile', recommendedDesignSystem: 'consumer-mobile' },
  'mobile-activity': { category: 'mobile', recommendedDesignSystem: 'consumer-mobile' },
  'desktop-editor': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'desktop-file-manager': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'desktop-inspector': { category: 'app', recommendedDesignSystem: 'saas-modern' },
  'dashboard-security': { category: 'dashboard', recommendedDesignSystem: 'dense-ops' },
  'dashboard-observability': { category: 'dashboard', recommendedDesignSystem: 'dense-ops' },
  'dashboard-marketing': { category: 'dashboard', recommendedDesignSystem: 'executive-analytics' },
  'dashboard-product': { category: 'dashboard', recommendedDesignSystem: 'executive-analytics' },
  'dashboard-infra': { category: 'dashboard', recommendedDesignSystem: 'dense-ops' },
  'deck-sales': { category: 'deck', recommendedDesignSystem: 'pitch-dark' },
  'deck-roadmap': { category: 'deck', recommendedDesignSystem: 'strategy-light' },
  'deck-launch': { category: 'deck', recommendedDesignSystem: 'pitch-dark' },
  'deck-board-update': { category: 'deck', recommendedDesignSystem: 'pitch-dark' },
  'report-audit': { category: 'report', recommendedDesignSystem: 'research-paper' },
  'report-qa': { category: 'report', recommendedDesignSystem: 'product-spec' },
  'report-strategy-memo': { category: 'report', recommendedDesignSystem: 'product-spec' },
  'report-research-synthesis': { category: 'report', recommendedDesignSystem: 'research-paper' },
  'image-campaign-board': { category: 'image', recommendedDesignSystem: 'brand-visual' },
  'image-social-pack': { category: 'image', recommendedDesignSystem: 'brand-visual' },
  'video-ad-storyboard': { category: 'video', recommendedDesignSystem: 'launch-motion' },
  'video-onboarding-flow': { category: 'video', recommendedDesignSystem: 'demo-storyboard' },
}

const DESIGN_SYSTEMS: Record<string, string[]> = {
  'studio-prototype': ['saas-modern', 'consumer-mobile', 'commerce-editorial', 'apple', 'linear', 'figma', 'glassmorphism', 'material'],
  'studio-dashboard': ['dense-ops', 'executive-analytics', 'ai-command', 'github', 'hud', 'dashboard'],
  'studio-deck': ['pitch-dark', 'strategy-light', 'editorial', 'brutalism'],
  'studio-report': ['research-paper', 'product-spec', 'minimal', 'enterprise'],
  'studio-image': ['brand-visual', 'product-mockup', 'friendly', 'luxury'],
  'studio-video': ['launch-motion', 'demo-storyboard', 'creative', 'gradient'],
}

const COMPONENTS: Record<string, string[]> = {
  'studio-prototype': ['hero', 'features', 'pricing', 'faq', 'testimonial', 'cta-band', 'app-shell', 'feature-grid', 'commerce-card', 'case-study-block', 'nav-shell', 'settings-panel', 'inbox-list', 'kanban-column', 'billing-table', 'mobile-frame', 'desktop-toolbar'],
  'studio-dashboard': ['sidebar', 'metric-card', 'chart-panel', 'table-panel', 'filter-bar', 'status-feed', 'insight-card', 'risk-list', 'sparkline-card', 'alert-table', 'log-stream', 'funnel-chart', 'security-score'],
  'studio-deck': ['slide-title', 'slide-section', 'slide-comparison', 'slide-metric', 'slide-timeline', 'slide-quote', 'slide-roadmap', 'slide-agenda', 'slide-ask', 'slide-status'],
  'studio-report': ['executive-summary', 'evidence-table', 'recommendation-card', 'decision-log', 'risk-register', 'qa-summary', 'memo-header'],
  'studio-image': ['prompt-card', 'style-frame', 'variant-grid', 'campaign-frame', 'social-tile'],
  'studio-video': ['storyboard-scene', 'shot-list', 'timeline-beat', 'ad-beat', 'onboarding-step'],
}

function skillPath(skill: string, ...parts: string[]): string {
  return join(BUILTIN_SKILLS_ROOT, skill, ...parts)
}

export function listStudioTemplates(): StudioTemplateDefinition[] {
  return [...DEFINITIONS, ...OPEN_DESIGN_DEFINITIONS].map(def => {
    const metadata = TEMPLATE_METADATA[def.id] ?? OPEN_DESIGN_TEMPLATE_METADATA[def.id] ?? { category: 'web' as const, recommendedDesignSystem: undefined }
    return {
      ...def,
      ...metadata,
      templatePath: skillPath(def.skill, 'templates', `${def.id}.html`),
      componentPaths: (COMPONENTS[def.skill] ?? []).map(component => skillPath(def.skill, 'components', `${component}.html`)),
    }
  })
}

export function getStudioTemplate(templateId: string): StudioTemplateDefinition | undefined {
  return listStudioTemplates().find(template => template.id === templateId)
}

export function readStudioTemplateHtml(templateId: string): string {
  const template = getStudioTemplate(templateId)
  if (!template) throw new Error(`Studio template not found: ${templateId}`)
  if (!existsSync(template.templatePath)) throw new Error(`Studio template file not found: ${templateId}`)
  return readFileSync(template.templatePath, 'utf-8')
}

export function readStudioComponentHtml(skill: string, preset: string): string | undefined {
  const path = skillPath(skill, 'components', `${preset}.html`)
  return existsSync(path) ? readFileSync(path, 'utf-8') : undefined
}

function designSystemPath(skill: string, id: string): string {
  return skillPath(skill, 'design-systems', `${id}.json`)
}

export function listStudioDesignSystems(): StudioDesignSystemDefinition[] {
  return Object.entries(DESIGN_SYSTEMS).flatMap(([skill, ids]) => ids.map(id => getStudioDesignSystem(id)).filter((item): item is StudioDesignSystemDefinition => Boolean(item)))
}

export function getStudioDesignSystem(id: string): StudioDesignSystemDefinition | undefined {
  for (const [skill, ids] of Object.entries(DESIGN_SYSTEMS)) {
    if (!ids.includes(id)) continue
    const path = designSystemPath(skill, id)
    if (!existsSync(path)) return undefined
    const parsed = JSON.parse(readFileSync(path, 'utf-8')) as StudioDesignSystemDefinition
    return parsed.id === id ? parsed : undefined
  }
  return undefined
}

// AUTO-GENERATED: Open Design normalized templates.
const OPEN_DESIGN_DEFINITIONS: Array<Omit<StudioTemplateDefinition, 'templatePath' | 'componentPaths' | 'category' | 'recommendedDesignSystem'>> = [
  { id: 'audio-jingle', title: 'Audio Jingle', description: 'Open Design Audio Jingle template normalized for Craft Studio motion workflows.', type: 'motion', skill: 'studio-video', tags: ['open-design', 'motion', 'motion'] },
  { id: 'blog-post', title: 'Blog Post', description: 'Open Design Blog Post template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'clinical-case-report', title: 'Clinical Case Report', description: 'Open Design Clinical Case Report template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'contact-widget', title: 'Contact Widget', description: 'Open Design Contact Widget template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'critique', title: 'Critique', description: 'Open Design Critique template normalized for Craft Studio critique workflows.', type: 'critique', skill: 'studio-report', tags: ['open-design', 'critique', 'critique'] },
  { id: 'dashboard', title: 'Dashboard', description: 'Open Design Dashboard template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'dating-web', title: 'Dating WEB', description: 'Open Design Dating WEB template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'dcf-valuation', title: 'DCF Valuation', description: 'Open Design DCF Valuation template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'digital-eguide', title: 'Digital Eguide', description: 'Open Design Digital Eguide template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'docs-page', title: 'Docs Page', description: 'Open Design Docs Page template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'email-marketing', title: 'Email Marketing', description: 'Open Design Email Marketing template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'eng-runbook', title: 'ENG Runbook', description: 'Open Design ENG Runbook template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'finance-report', title: 'Finance Report', description: 'Open Design Finance Report template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'flowai-live-dashboard-template', title: 'Flowai Live Dashboard Template', description: 'Open Design Flowai Live Dashboard Template template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'gamified-app', title: 'Gamified APP', description: 'Open Design Gamified APP template normalized for Craft Studio app workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'app', 'prototype'] },
  { id: 'github-dashboard', title: 'Github Dashboard', description: 'Open Design Github Dashboard template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'guizang-ppt', title: 'Guizang PPT', description: 'Open Design Guizang PPT template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'hr-onboarding', title: 'HR Onboarding', description: 'Open Design HR Onboarding template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'html-ppt', title: 'Html PPT', description: 'Open Design Html PPT template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-course-module', title: 'Html PPT Course Module', description: 'Open Design Html PPT Course Module template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-graphify-dark-graph', title: 'Html PPT Graphify Dark Graph', description: 'Open Design Html PPT Graphify Dark Graph template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-hermes-cyber-terminal', title: 'Html PPT Hermes Cyber Terminal', description: 'Open Design Html PPT Hermes Cyber Terminal template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-knowledge-arch-blueprint', title: 'Html PPT Knowledge Arch Blueprint', description: 'Open Design Html PPT Knowledge Arch Blueprint template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-obsidian-claude-gradient', title: 'Html PPT Obsidian Claude Gradient', description: 'Open Design Html PPT Obsidian Claude Gradient template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-pitch-deck', title: 'Html PPT Pitch Deck', description: 'Open Design Html PPT Pitch Deck template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-presenter-mode-reveal', title: 'Html PPT Presenter Mode Reveal', description: 'Open Design Html PPT Presenter Mode Reveal template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-product-launch', title: 'Html PPT Product Launch', description: 'Open Design Html PPT Product Launch template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-taste-brutalist', title: 'Html PPT Taste Brutalist', description: 'Open Design Html PPT Taste Brutalist template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-taste-editorial', title: 'Html PPT Taste Editorial', description: 'Open Design Html PPT Taste Editorial template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-tech-sharing', title: 'Html PPT Tech Sharing', description: 'Open Design Html PPT Tech Sharing template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-testing-safety-alert', title: 'Html PPT Testing Safety Alert', description: 'Open Design Html PPT Testing Safety Alert template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-weekly-report', title: 'Html PPT Weekly Report', description: 'Open Design Html PPT Weekly Report template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-xhs-pastel-card', title: 'Html PPT XHS Pastel Card', description: 'Open Design Html PPT XHS Pastel Card template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-xhs-white-editorial', title: 'Html PPT XHS White Editorial', description: 'Open Design Html PPT XHS White Editorial template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-8-bit-orbit', title: 'Html PPT Zhangzara 8 BIT Orbit', description: 'Open Design Html PPT Zhangzara 8 BIT Orbit template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-biennale-yellow', title: 'Html PPT Zhangzara Biennale Yellow', description: 'Open Design Html PPT Zhangzara Biennale Yellow template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-block-frame', title: 'Html PPT Zhangzara Block Frame', description: 'Open Design Html PPT Zhangzara Block Frame template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-blue-professional', title: 'Html PPT Zhangzara Blue Professional', description: 'Open Design Html PPT Zhangzara Blue Professional template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-bold-poster', title: 'Html PPT Zhangzara Bold Poster', description: 'Open Design Html PPT Zhangzara Bold Poster template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-broadside', title: 'Html PPT Zhangzara Broadside', description: 'Open Design Html PPT Zhangzara Broadside template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-capsule', title: 'Html PPT Zhangzara Capsule', description: 'Open Design Html PPT Zhangzara Capsule template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-cartesian', title: 'Html PPT Zhangzara Cartesian', description: 'Open Design Html PPT Zhangzara Cartesian template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-cobalt-grid', title: 'Html PPT Zhangzara Cobalt Grid', description: 'Open Design Html PPT Zhangzara Cobalt Grid template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-coral', title: 'Html PPT Zhangzara Coral', description: 'Open Design Html PPT Zhangzara Coral template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-creative-mode', title: 'Html PPT Zhangzara Creative Mode', description: 'Open Design Html PPT Zhangzara Creative Mode template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-daisy-days', title: 'Html PPT Zhangzara Daisy Days', description: 'Open Design Html PPT Zhangzara Daisy Days template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-editorial-tri-tone', title: 'Html PPT Zhangzara Editorial TRI Tone', description: 'Open Design Html PPT Zhangzara Editorial TRI Tone template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-grove', title: 'Html PPT Zhangzara Grove', description: 'Open Design Html PPT Zhangzara Grove template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-long-table', title: 'Html PPT Zhangzara Long Table', description: 'Open Design Html PPT Zhangzara Long Table template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-mat', title: 'Html PPT Zhangzara MAT', description: 'Open Design Html PPT Zhangzara MAT template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-monochrome', title: 'Html PPT Zhangzara Monochrome', description: 'Open Design Html PPT Zhangzara Monochrome template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-neo-grid-bold', title: 'Html PPT Zhangzara NEO Grid Bold', description: 'Open Design Html PPT Zhangzara NEO Grid Bold template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-peoples-platform', title: 'Html PPT Zhangzara Peoples Platform', description: 'Open Design Html PPT Zhangzara Peoples Platform template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-pin-and-paper', title: 'Html PPT Zhangzara PIN AND Paper', description: 'Open Design Html PPT Zhangzara PIN AND Paper template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-pink-script', title: 'Html PPT Zhangzara Pink Script', description: 'Open Design Html PPT Zhangzara Pink Script template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-playful', title: 'Html PPT Zhangzara Playful', description: 'Open Design Html PPT Zhangzara Playful template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-raw-grid', title: 'Html PPT Zhangzara RAW Grid', description: 'Open Design Html PPT Zhangzara RAW Grid template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-retro-windows', title: 'Html PPT Zhangzara Retro Windows', description: 'Open Design Html PPT Zhangzara Retro Windows template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-retro-zine', title: 'Html PPT Zhangzara Retro Zine', description: 'Open Design Html PPT Zhangzara Retro Zine template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-sakura-chroma', title: 'Html PPT Zhangzara Sakura Chroma', description: 'Open Design Html PPT Zhangzara Sakura Chroma template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-scatterbrain', title: 'Html PPT Zhangzara Scatterbrain', description: 'Open Design Html PPT Zhangzara Scatterbrain template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-signal', title: 'Html PPT Zhangzara Signal', description: 'Open Design Html PPT Zhangzara Signal template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-soft-editorial', title: 'Html PPT Zhangzara Soft Editorial', description: 'Open Design Html PPT Zhangzara Soft Editorial template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-stencil-tablet', title: 'Html PPT Zhangzara Stencil Tablet', description: 'Open Design Html PPT Zhangzara Stencil Tablet template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-studio', title: 'Html PPT Zhangzara Studio', description: 'Open Design Html PPT Zhangzara Studio template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'html-ppt-zhangzara-vellum', title: 'Html PPT Zhangzara Vellum', description: 'Open Design Html PPT Zhangzara Vellum template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'hyperframes', title: 'Hyperframes', description: 'Open Design Hyperframes template normalized for Craft Studio motion workflows.', type: 'motion', skill: 'studio-video', tags: ['open-design', 'motion', 'motion'] },
  { id: 'ib-pitch-book', title: 'IB Pitch Book', description: 'Open Design IB Pitch Book template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'image-poster', title: 'Image Poster', description: 'Open Design Image Poster template normalized for Craft Studio image workflows.', type: 'image-prompt', skill: 'studio-image', tags: ['open-design', 'image', 'image-prompt'] },
  { id: 'invoice', title: 'Invoice', description: 'Open Design Invoice template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'kami-deck', title: 'Kami Deck', description: 'Open Design Kami Deck template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'kami-landing', title: 'Kami Landing', description: 'Open Design Kami Landing template normalized for Craft Studio web workflows.', type: 'landing-page', skill: 'studio-prototype', tags: ['open-design', 'web', 'landing-page'] },
  { id: 'od-kanban-board', title: 'Kanban Board', description: 'Open Design Kanban Board template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'last30days', title: 'Last30days', description: 'Open Design Last30days template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'live-artifact', title: 'Live Artifact', description: 'Open Design Live Artifact template normalized for Craft Studio critique workflows.', type: 'critique', skill: 'studio-report', tags: ['open-design', 'critique', 'critique'] },
  { id: 'live-dashboard', title: 'Live Dashboard', description: 'Open Design Live Dashboard template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'magazine-poster', title: 'Magazine Poster', description: 'Open Design Magazine Poster template normalized for Craft Studio image workflows.', type: 'image-prompt', skill: 'studio-image', tags: ['open-design', 'image', 'image-prompt'] },
  { id: 'meeting-notes', title: 'Meeting Notes', description: 'Open Design Meeting Notes template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'mobile-app', title: 'Mobile APP', description: 'Open Design Mobile APP template normalized for Craft Studio mobile workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'mobile', 'prototype'] },
  { id: 'mobile-onboarding', title: 'Mobile Onboarding', description: 'Open Design Mobile Onboarding template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'motion-frames', title: 'Motion Frames', description: 'Open Design Motion Frames template normalized for Craft Studio motion workflows.', type: 'motion', skill: 'studio-video', tags: ['open-design', 'motion', 'motion'] },
  { id: 'open-design-landing', title: 'Open Design Landing', description: 'Open Design Open Design Landing template normalized for Craft Studio web workflows.', type: 'landing-page', skill: 'studio-prototype', tags: ['open-design', 'web', 'landing-page'] },
  { id: 'open-design-landing-deck', title: 'Open Design Landing Deck', description: 'Open Design Open Design Landing Deck template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'orbit-general', title: 'Orbit General', description: 'Open Design Orbit General template normalized for Craft Studio app workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'app', 'prototype'] },
  { id: 'orbit-github', title: 'Orbit Github', description: 'Open Design Orbit Github template normalized for Craft Studio app workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'app', 'prototype'] },
  { id: 'orbit-gmail', title: 'Orbit Gmail', description: 'Open Design Orbit Gmail template normalized for Craft Studio app workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'app', 'prototype'] },
  { id: 'orbit-linear', title: 'Orbit Linear', description: 'Open Design Orbit Linear template normalized for Craft Studio app workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'app', 'prototype'] },
  { id: 'orbit-notion', title: 'Orbit Notion', description: 'Open Design Orbit Notion template normalized for Craft Studio app workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'app', 'prototype'] },
  { id: 'pm-spec', title: 'PM Spec', description: 'Open Design PM Spec template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'pricing-page', title: 'Pricing Page', description: 'Open Design Pricing Page template normalized for Craft Studio web workflows.', type: 'landing-page', skill: 'studio-prototype', tags: ['open-design', 'web', 'landing-page'] },
  { id: 'replit-deck', title: 'Replit Deck', description: 'Open Design Replit Deck template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'saas-landing', title: 'Saas Landing', description: 'Open Design Saas Landing template normalized for Craft Studio web workflows.', type: 'landing-page', skill: 'studio-prototype', tags: ['open-design', 'web', 'landing-page'] },
  { id: 'simple-deck', title: 'Simple Deck', description: 'Open Design Simple Deck template normalized for Craft Studio deck workflows.', type: 'deck', skill: 'studio-deck', tags: ['open-design', 'deck', 'deck'] },
  { id: 'social-carousel', title: 'Social Carousel', description: 'Open Design Social Carousel template normalized for Craft Studio image workflows.', type: 'image-prompt', skill: 'studio-image', tags: ['open-design', 'image', 'image-prompt'] },
  { id: 'social-media-dashboard', title: 'Social Media Dashboard', description: 'Open Design Social Media Dashboard template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'social-media-matrix-tracker-template', title: 'Social Media Matrix Tracker Template', description: 'Open Design Social Media Matrix Tracker Template template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'sprite-animation', title: 'Sprite Animation', description: 'Open Design Sprite Animation template normalized for Craft Studio motion workflows.', type: 'motion', skill: 'studio-video', tags: ['open-design', 'motion', 'motion'] },
  { id: 'team-okrs', title: 'Team Okrs', description: 'Open Design Team Okrs template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'trading-analysis-dashboard-template', title: 'Trading Analysis Dashboard Template', description: 'Open Design Trading Analysis Dashboard Template template normalized for Craft Studio dashboard workflows.', type: 'dashboard', skill: 'studio-dashboard', tags: ['open-design', 'dashboard', 'dashboard'] },
  { id: 'tweaks', title: 'Tweaks', description: 'Open Design Tweaks template normalized for Craft Studio critique workflows.', type: 'critique', skill: 'studio-report', tags: ['open-design', 'critique', 'critique'] },
  { id: 'video-shortform', title: 'Video Shortform', description: 'Open Design Video Shortform template normalized for Craft Studio motion workflows.', type: 'motion', skill: 'studio-video', tags: ['open-design', 'motion', 'motion'] },
  { id: 'waitlist-page', title: 'Waitlist Page', description: 'Open Design Waitlist Page template normalized for Craft Studio web workflows.', type: 'landing-page', skill: 'studio-prototype', tags: ['open-design', 'web', 'landing-page'] },
  { id: 'web-prototype', title: 'WEB Prototype', description: 'Open Design WEB Prototype template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'web-prototype-taste-brutalist', title: 'WEB Prototype Taste Brutalist', description: 'Open Design WEB Prototype Taste Brutalist template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'web-prototype-taste-editorial', title: 'WEB Prototype Taste Editorial', description: 'Open Design WEB Prototype Taste Editorial template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'web-prototype-taste-soft', title: 'WEB Prototype Taste Soft', description: 'Open Design WEB Prototype Taste Soft template normalized for Craft Studio web workflows.', type: 'prototype', skill: 'studio-prototype', tags: ['open-design', 'web', 'prototype'] },
  { id: 'weekly-update', title: 'Weekly Update', description: 'Open Design Weekly Update template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
  { id: 'wireframe-sketch', title: 'Wireframe Sketch', description: 'Open Design Wireframe Sketch template normalized for Craft Studio image workflows.', type: 'image-prompt', skill: 'studio-image', tags: ['open-design', 'image', 'image-prompt'] },
  { id: 'x-research', title: 'X Research', description: 'Open Design X Research template normalized for Craft Studio document workflows.', type: 'document', skill: 'studio-report', tags: ['open-design', 'document', 'document'] },
]
// END AUTO-GENERATED: Open Design normalized templates

// AUTO-GENERATED: Open Design template metadata.
const OPEN_DESIGN_TEMPLATE_METADATA: Record<string, { category: StudioTemplateCategory; recommendedDesignSystem: string }> = {
  'audio-jingle': { category: 'motion', recommendedDesignSystem: 'gradient' },
  'blog-post': { category: 'web', recommendedDesignSystem: 'minimal' },
  'clinical-case-report': { category: 'document', recommendedDesignSystem: 'minimal' },
  'contact-widget': { category: 'web', recommendedDesignSystem: 'linear' },
  'critique': { category: 'critique', recommendedDesignSystem: 'minimal' },
  'dashboard': { category: 'dashboard', recommendedDesignSystem: 'dashboard' },
  'dating-web': { category: 'web', recommendedDesignSystem: 'linear' },
  'dcf-valuation': { category: 'document', recommendedDesignSystem: 'enterprise' },
  'digital-eguide': { category: 'web', recommendedDesignSystem: 'minimal' },
  'docs-page': { category: 'web', recommendedDesignSystem: 'linear' },
  'email-marketing': { category: 'web', recommendedDesignSystem: 'minimal' },
  'eng-runbook': { category: 'document', recommendedDesignSystem: 'enterprise' },
  'finance-report': { category: 'document', recommendedDesignSystem: 'enterprise' },
  'flowai-live-dashboard-template': { category: 'dashboard', recommendedDesignSystem: 'dashboard' },
  'gamified-app': { category: 'app', recommendedDesignSystem: 'linear' },
  'github-dashboard': { category: 'dashboard', recommendedDesignSystem: 'github' },
  'guizang-ppt': { category: 'deck', recommendedDesignSystem: 'linear' },
  'hr-onboarding': { category: 'document', recommendedDesignSystem: 'linear' },
  'html-ppt': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-course-module': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-graphify-dark-graph': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-hermes-cyber-terminal': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-knowledge-arch-blueprint': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-obsidian-claude-gradient': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-pitch-deck': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-presenter-mode-reveal': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-product-launch': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-taste-brutalist': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-taste-editorial': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-tech-sharing': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-testing-safety-alert': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-weekly-report': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-xhs-pastel-card': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-xhs-white-editorial': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-8-bit-orbit': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-zhangzara-biennale-yellow': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-block-frame': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-blue-professional': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-bold-poster': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-zhangzara-broadside': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-capsule': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-cartesian': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-cobalt-grid': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-zhangzara-coral': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-creative-mode': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-daisy-days': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-editorial-tri-tone': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-grove': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-long-table': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-mat': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-monochrome': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-neo-grid-bold': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-zhangzara-peoples-platform': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-pin-and-paper': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-pink-script': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-playful': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-raw-grid': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-retro-windows': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-retro-zine': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-sakura-chroma': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-scatterbrain': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-signal': { category: 'deck', recommendedDesignSystem: 'brutalism' },
  'html-ppt-zhangzara-soft-editorial': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'html-ppt-zhangzara-stencil-tablet': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-studio': { category: 'deck', recommendedDesignSystem: 'linear' },
  'html-ppt-zhangzara-vellum': { category: 'deck', recommendedDesignSystem: 'editorial' },
  'hyperframes': { category: 'motion', recommendedDesignSystem: 'gradient' },
  'ib-pitch-book': { category: 'deck', recommendedDesignSystem: 'linear' },
  'image-poster': { category: 'image', recommendedDesignSystem: 'editorial' },
  'invoice': { category: 'document', recommendedDesignSystem: 'enterprise' },
  'kami-deck': { category: 'deck', recommendedDesignSystem: 'linear' },
  'kami-landing': { category: 'web', recommendedDesignSystem: 'linear' },
  'od-kanban-board': { category: 'web', recommendedDesignSystem: 'minimal' },
  'last30days': { category: 'web', recommendedDesignSystem: 'minimal' },
  'live-artifact': { category: 'critique', recommendedDesignSystem: 'minimal' },
  'live-dashboard': { category: 'dashboard', recommendedDesignSystem: 'dashboard' },
  'magazine-poster': { category: 'image', recommendedDesignSystem: 'editorial' },
  'meeting-notes': { category: 'document', recommendedDesignSystem: 'linear' },
  'mobile-app': { category: 'mobile', recommendedDesignSystem: 'apple' },
  'mobile-onboarding': { category: 'document', recommendedDesignSystem: 'linear' },
  'motion-frames': { category: 'motion', recommendedDesignSystem: 'gradient' },
  'open-design-landing': { category: 'web', recommendedDesignSystem: 'linear' },
  'open-design-landing-deck': { category: 'deck', recommendedDesignSystem: 'linear' },
  'orbit-general': { category: 'app', recommendedDesignSystem: 'linear' },
  'orbit-github': { category: 'app', recommendedDesignSystem: 'linear' },
  'orbit-gmail': { category: 'app', recommendedDesignSystem: 'linear' },
  'orbit-linear': { category: 'app', recommendedDesignSystem: 'linear' },
  'orbit-notion': { category: 'app', recommendedDesignSystem: 'linear' },
  'pm-spec': { category: 'document', recommendedDesignSystem: 'linear' },
  'pricing-page': { category: 'web', recommendedDesignSystem: 'linear' },
  'replit-deck': { category: 'deck', recommendedDesignSystem: 'linear' },
  'saas-landing': { category: 'web', recommendedDesignSystem: 'linear' },
  'simple-deck': { category: 'deck', recommendedDesignSystem: 'linear' },
  'social-carousel': { category: 'image', recommendedDesignSystem: 'creative' },
  'social-media-dashboard': { category: 'dashboard', recommendedDesignSystem: 'friendly' },
  'social-media-matrix-tracker-template': { category: 'dashboard', recommendedDesignSystem: 'friendly' },
  'sprite-animation': { category: 'motion', recommendedDesignSystem: 'creative' },
  'team-okrs': { category: 'document', recommendedDesignSystem: 'linear' },
  'trading-analysis-dashboard-template': { category: 'dashboard', recommendedDesignSystem: 'dashboard' },
  'tweaks': { category: 'critique', recommendedDesignSystem: 'minimal' },
  'video-shortform': { category: 'motion', recommendedDesignSystem: 'gradient' },
  'waitlist-page': { category: 'web', recommendedDesignSystem: 'linear' },
  'web-prototype': { category: 'web', recommendedDesignSystem: 'linear' },
  'web-prototype-taste-brutalist': { category: 'web', recommendedDesignSystem: 'brutalism' },
  'web-prototype-taste-editorial': { category: 'web', recommendedDesignSystem: 'editorial' },
  'web-prototype-taste-soft': { category: 'web', recommendedDesignSystem: 'linear' },
  'weekly-update': { category: 'document', recommendedDesignSystem: 'linear' },
  'wireframe-sketch': { category: 'image', recommendedDesignSystem: 'minimal' },
  'x-research': { category: 'document', recommendedDesignSystem: 'minimal' },
}
// END AUTO-GENERATED: Open Design template metadata
